config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/chat',    to: 'static_pages#chat'
  post 'messages', to: 'messages#create'  
  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :microposts,          only: [:create, :destroy]  
  resources :relationships,       only: [:create, :destroy]  
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end

  end

  def help
  end

  def about
  end

  def contact
  end
  
  
  def chat
    @messages = Message.all
    @message = Message.new
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This is the Ruby on rails sample app with the ability to sign up, sign in, send messages in a chat room,  post, follow and unfollow other users.</p>

app/views/static_pages/chat.html.erb
<div class="jumbotron">
  <h1 style="text=align:center">Live Chat</h1>
<div class="col-md-12 col-lg-12" id="chatbox" style="height: 250px; overflow-y: scroll;">

    <% @messages.each do |message| %>
    <%= render 'messages/message', message: message, currentUser: current_user.id, creator: message.user.id %>
    <% end %>
  </div>
    <%= form_for  (@message), remote: true do |f| %>
      <div class="input-group">
        <%= f.text_field  :body, placeholder: "Send a message... ", class: "form-control", label: false, wrapper: false, autocomplete:'off' %>
        <div class="input-group-prepend">
          <%= f.submit "Send", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
</div>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>No content present yet.</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
   
  </div>
<% else %>

<div class="center jumbotron">
  <h1>Welcome to the Ruby App</h1>
    
  <h2>
    This is the home page for the Ruby on Rails App</a>
    sample application.
  </h2>

    <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>