config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/chat',    to: 'static_pages#chat'
  post 'messages', to: 'messages#create'  
  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :microposts,          only: [:create, :destroy]  
  resources :relationships,       only: [:create, :destroy]  
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
  <small>
    The Ruby on Rails App</a>
    by <a href="#">Femi Lawal</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_guest.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ruby App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
                <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Chats", chat_path %></li>          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      
      </ul>
    </nav>
 
  </div>
  
</header>
    <div>

    </div>       

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
  </head>

  <body>
       <div class="container">
    <%= render 'layouts/guest' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>    
        </div>
  </body>
</html>